### ISSUE TITLE
ERC20 Token Allowance Amount - Max Value vs Custom value

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-js-sdk#19]
Currently, you can only approve `MaxUint256` Wei, which is practically unlimited. In some cases, end-users may want to only allow a specific amount to be approved, for example before initiating a one-time Give. It'd be neat if the function could optionally accept an `amount` param, while using `MaxUint256` as the default.

**Comment by gh0stwheel** [comment]
I've considered this as well. However, I worry that the downside is that by offering the option, we may push many developers towards a UX where their end users must continuously increment the amount that is approved, leading to more UX complexity and another whole aspect of the protocol that the end users have to keep track of and think about.

 @CodeSandwich @evvvritt -- any thoughts here?

**Comment by CodeSandwich** [comment]
Dai provides no good solution. We can approve in a separate transaction and then it costs money to do especially in case of an EOA, because it requires making 2 transactions. Usually web3 apps try to limit the UX nastiness by trying to make the user make an unlimited approval. The other solution are signed documents allowing approving in-flight, in the same transaction which calls drips.  Unfortunately Dai only supports unlimited approvals this way.

**Comment by efstajas** [comment]
When we were building rad.lol, where you were able to mint an NFT from a drips community through a one-time give, we opted to make the approval only for the amount that the user selected, because in our flow the user first entered their desired donation amount, then gave approval, and eventually send the mint TX. In this scenario, it was very unlikely that users would want to donate more than once and mint multiple NFTs, and it felt problematic to approve a practically infinite amount of DAI (which the user can easily check as part of the TX confirmation in MetaMask) right after the user entered a specific amount to donate. As an end-user, in this scenario I would think "hmm, why would i approve it for _all_ my DAI forever" and possibly drop out.

I realize that this isn't 100% relevant here as the SDK is not intended for interacting with communities, and the NFT reward feature isn't in scope, but I can imagine similar scenarios as soon as one-time Gives are supported in the SDK.

That said, I'd 100% understand the decision to not support specific allowance amounts in order to avoid friction as in the vast majority of use-cases, a one-time approval for the max amount probably results in a smoother end user experience.

**Comment by evvvritt** [comment]
Is it a lot of overhead to support the override? I personally support the flexibility. Or we wait until there's more requests for this feature.

**Comment by gh0stwheel** [comment]
There are just tradeoffs here between usability and security.

Let's review this for ERC-20s in general after v0.2 has been shipped.

**Comment by jtourkos** [comment]
I think now is the time to finalize this.

Any objections to keeping it as are (max allowance) @gh0stwheel, @efstajas, @evvvritt?
If not, let's close it.

If you think we should do it - at some point -  then could you indicate if you think it's for the "alpha," "beta," etc. versions, to prioritize?

We can always change it in the future (potentially introducing breaking changes).

**Comment by gh0stwheel** [comment]
My vote for the SDK would be to just keep it as is (i.e. approval is always for the maximum amount). 

If developers want to roll their own code to do something different, they can totally do that. The approval calls are on contracts other than ours, so the reality is that it's relatively easy to approve for less if you want to do that as an advanced developer.

**Comment by jtourkos** [comment]
Alright, I am closing this. If we get related feedback, we will reconsider this.
