### ISSUE TITLE
Add a function for collecting funds

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-js-sdk#20]
Would be fantastic if the SDK had a `collect` function to make allowing end-users to collect their funds easy. Relevant code in drips-app: https://github.com/radicle-dev/drips-app/blob/69f4278392103274aaad57e766a7ea7133a527b7/src/store/index.js#L807-L830

**Comment by jtourkos** [comment]
Hey @efstajas @gh0stwheel! Just started working on this. 🤓

Quick question. In the [code snippet above](https://github.com/radicle-dev/drips-app/blob/69f4278392103274aaad57e766a7ea7133a527b7/src/store/index.js#L807-L830) I see that we check if the collection happens from a project or the hubs contract.

Do we want to expose the same functionality  and support _both_ collections? Or just the "lowel-level" of the Hub?

What do you say?

**Comment by gh0stwheel** [comment]
Just the "lower-level" of the Hub for now.

In the first versions of the SDK we're not including anything related to the membership/NFT functionality, because the future roadmap of that functionality is uncertain.
