### ISSUE TITLE
updateUserDrips and updateUserSplits are properties instead of functions in DripsClient

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/drips-js-sdk#23]
I think this is just a mistake. We should change them into functions and test.

**Comment by jtourkos** [comment]
This is done as part of [this](https://github.com/radicle-dev/drips-js-sdk/commit/0931ce3e9df1dbf2b7a230e29fe45374daea4ade#diff-041379c7578e54948cebe69ca90a63830c72601878e428392047d3cde955313f) commit and it's merged.
Closing the issue.
