### ISSUE TITLE
Add a Page in the Docusaurus Docs About How Dev in Examples Works and How Tags Are Used

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/drips-js-sdk#28]
* Describe how to set up local development using npm link (reference this medium article https://medium.com/@AidThompsin/how-to-npm-link-to-a-local-version-of-your-dependency-84e82126667a)
* What is the dev process for code in examples directory?
* How does testing work?
* When do we create new tags and update examples code to point to them?

**Comment by jtourkos** [comment]
Closing this since official docs start to take shape.
