### ISSUE TITLE
Add Integration Tests

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/drips-js-sdk#30]
We now have *unit tests* for DripsClient, but eventually we would also like to have integration tests which offer more nuanced testing of functionality that depends on blockchain state, or a mock of it.

There are several approaches to this:

1) Mock blockchain state in the local environment
2) Run a full single-node EVM-based blockchain locally to test against
3) Test against a real-world EVM-based testnet like Rinkeby

The first part of resolving this issue will be to research and select an approach out of the above approaches and the second part of resolving this issue will be to write integration tests for DripsClient based on that approach.

**Comment by jtourkos** [comment]
A good enough amount of tests is added, closing.
