### ISSUE TITLE
Initializing the SDK with the network name is a bit confusing & sometimes inconsistent

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-js-sdk#34]
It's now mandatory to pass `networkName` to the drips client constructor: https://github.com/radicle-dev/drips-js-sdk/blob/main/src/dripsclient.ts#L20

1. The contract addresses are initialized for the given network name when the class is constructed, but `this.networkId` [is later populated from the passed provider's network](https://github.com/radicle-dev/drips-js-sdk/blob/main/src/dripsclient.ts#L33) on call to `connect`. This might lead to a confusing situation where contract calls fail with a nondescript error message because the user accidentally passed a different network name to the one their provider is connected to. IMO ideally the user would pass the `network.chainId` to the constructor, and `this.networkId` should be set then — and if the provider's network ID later doesn't match `this.chainId` on call to `connect`, it should throw an error.
2. Currently, the user needs to pass `networkName` as a string, but the [expected network names](https://github.com/radicle-dev/drips-js-sdk/blob/973599caf3013a2ac56155f11b8cd2426ff263d1/src/contracts.ts#L1-L6) don't match the name returned by calling `provider.network.name`. For example, my Web3Provider calls ethereum mainnet `homestead`, whereas the drips SDK expects `mainnet`. Since [chain IDs are standardised as numbers](https://chainlist.org/), IMO it'd be a lot better to just accept the chainId as a number, and throw an explicit error if the passed ID is an unsupported network. Otherwise, the user needs to create their own chainId <> networkName mapping for the drips SDK.

**Comment by evvvritt** [comment]
Also agree with Jason on using `chainId` and would consider this high priority.

**Comment by jtourkos** [comment]
Closing the issue as part of [this PR](https://github.com/radicle-dev/drips-js-sdk/pull/36).
