### ISSUE TITLE
Review Contents of utils.ts and Only Export Select Functions Instead of All / Remove Unused Functions

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/drips-js-sdk#5]

**Comment by jtourkos** [comment]
- Add unit tests where necessary

**Comment by gh0stwheel** [comment]
Also decide whether these utils are intended for end users or for the SDK, or both.

**Comment by jtourkos** [comment]
Going through the utility methods (to clean up what is necessary and what is not), the _validation logic_ seems to make the most sense to be shared at this stage. More precisely the following methods:

- `validateDrips`
- `validateSplits`
- `validateAddress`

`utils` were extracted from the drips app while implementing the first version of the SDK, so the rest of the functionality it [exposes](https://github.com/radicle-dev/drips-js-sdk/blob/v0.1.1/src/utils.ts) is somehow _dedicated_ to the drips app use case.

(Note also that, the ~same methods are still implemented in the [drips app](https://github.com/radicle-dev/drips-app/blob/master/src/utils.js) codebase).

In my opinion, the SDK should expose more _generic_ utility methods covering a wider range of scenarios.
The calling side can implement, specific to their needs, utilities.

Given the all the above I suggest proceeding as follows:

1. Now - Remove everything else besides the validation methods mentioned before - the Drips app can still implement its own utilities and reuse the validators (@evvvritt).
2. Next version(s) - Add more generic utilities. Any suggestions already, even better 🙌 - [Related issue](https://github.com/radicle-dev/drips-js-sdk/issues/17).

(@gh0stwheel)
