### ISSUE TITLE
Determine Best Public/private Keyword Practices to Use for DripsClient Members

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/drips-js-sdk#9]
@itourkogiorgis says:

"I understand that some methods require the signer to exist (approveDAIContract) and some others for the address to exist (getAllowance), etc. But since the methods do not accept these dependencies as parameters themselves, but instead, they retrieve them from the provider object passed via the constructor, would it make sense to:

Encapsulate these properties (signer, address, networkId) by having public getters and private setters?"

@mattosborn says:

This depends on how you want this to look and behave for lib users.

Do lib users need access to these fields at all?
Is this for core functionality or just for debugging?
If this is for core functionality - is exposing this definitely the best way to achieve this?
Do you want users to have write access? Do you want to enforce this?
Depending on the answer to those questions you can use some combination of accessors, TS private or JS # to get the result you want. Some examples:

Public getter and private setter - private is not used in JavaScript and the TypeScript compiler strips these out. Lib consumers using TS should encounter compiler errors when trying to set, but JS consumers would be able to both get and set without error.
Public getter to access a regular field. e.g get signer() returning this._signer, (with no set definition). JS lib consumers would still be able to access/modify this._signer but it would be clear from the naming that it is intended as private and so would be unlikely to be misused.
Public getter to access a private field. Same as above but the # operator can be used to create private class fields, so lib consumers would have no way to modify the underlying variable.
An actual private field using '#'. If you really want it to be private, and there's no case where access might be useful for debugging, then you could just make it fully private.

**Comment by jtourkos** [comment]
Related PR: https://github.com/radicle-dev/drips-js-sdk/pull/40
